function escapePdfText(str: string): string {
  return str.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function wrapLines(text: string, maxChars: number = 82): string[] {
  const paragraphs = text.split("\n");
  const lines: string[] = [];
  for (const para of paragraphs) {
    if (para.trim().length === 0) {
      lines.push("");
      continue;
    }
    const words = para.split(/\s+/);
    let currentLine = "";
    for (const word of words) {
      if ((currentLine + " " + word).trim().length <= maxChars) {
        currentLine = (currentLine + " " + word).trim();
      } else {
        if (currentLine) lines.push(currentLine);
        currentLine = word;
      }
    }
    if (currentLine) lines.push(currentLine);
  }
  return lines;
}

export function buildRealPdfFile(filename: string, pagesContent: Array<{ title: string; body: string }>): File {
  const objects: string[] = [];
  const addObject = (content: string) => {
    objects.push(content);
    return objects.length;
  };

  const catalogId = addObject("");
  const pagesTreeId = addObject("");
  const fontId = addObject(`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`);
  const boldFontId = addObject(`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>`);

  const pageIds: number[] = [];

  pagesContent.forEach((page, pageIdx) => {
    const wrapped = wrapLines(page.body, 80);
    const streamLines: string[] = [
      "BT",
      `/F2 14 Tf`,
      `50 750 Td`,
      `(${escapePdfText(page.title)}) Tj`,
      `/F1 10.5 Tf`,
      `0 -24 Td`,
    ];

    wrapped.forEach((line) => {
      streamLines.push(`(${escapePdfText(line)}) Tj`);
      streamLines.push(`0 -15 Td`);
    });

    streamLines.push(`0 -20 Td`);
    streamLines.push(`(Page ${pageIdx + 1} of ${pagesContent.length} - Lecture Notes) Tj`);
    streamLines.push("ET");

    const streamContent = streamLines.join("\n");
    const contentId = addObject(
      `<< /Length ${streamContent.length} >>\nstream\n${streamContent}\nendstream`
    );

    const pageId = addObject(
      `<< /Type /Page /Parent ${pagesTreeId} 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 ${fontId} 0 R /F2 ${boldFontId} 0 R >> >> /Contents ${contentId} 0 R >>`
    );
    pageIds.push(pageId);
  });

  objects[catalogId - 1] = `<< /Type /Catalog /Pages ${pagesTreeId} 0 R >>`;
  objects[pagesTreeId - 1] = `<< /Type /Pages /Kids [${pageIds.map((id) => `${id} 0 R`).join(" ")}] /Count ${pageIds.length} >>`;

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [0];

  for (let i = 0; i < objects.length; i++) {
    offsets.push(pdf.length);
    pdf += `${i + 1} 0 obj\n${objects[i]}\nendobj\n`;
  }

  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += `0000000000 65535 f \n`;
  for (let i = 1; i <= objects.length; i++) {
    const offStr = String(offsets[i]).padStart(10, "0");
    pdf += `${offStr} 00000 n \n`;
  }

  pdf += `trailer\n<< /Size ${objects.length + 1} /Root ${catalogId} 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  const encoder = new TextEncoder();
  const bytes = encoder.encode(pdf);
  return new File([bytes], filename, { type: "application/pdf" });
}

export const SAMPLE_LECTURE_DECKS = [
  {
    id: "os_virtual_memory",
    label: "CS 301: Operating Systems — Virtual Memory & Paging.pdf",
    courseTag: "CS 301 Operating Systems",
    filename: "CS301_Virtual_Memory_and_Paging_Lecture.pdf",
    pages: [
      {
        title: "Lecture 1: Virtual Memory Architecture & Demand Paging",
        body: `Virtual memory is a memory management technique of an operating system that provides an idealized abstraction of the storage resources that are actually available on a given machine, creating the illusion to users of a very large main memory.

The core intuition behind virtual memory is separating logical memory as perceived by the programmer from physical RAM frames. Programs reference virtual addresses, and the Memory Management Unit (MMU) translates each virtual address into a physical frame address at runtime.

In a paged virtual memory system, the virtual address space is divided into fixed-size blocks called Pages (typically 4 KB in modern x86-64 architectures), while physical main memory is divided into fixed-size blocks of the exact same size called Frames.

A virtual address generated by the CPU is split into two components:
1. Virtual Page Number (VPN): High-order bits used as an index into the Page Table.
2. Page Offset: Low-order bits (for a 4 KB page, the lower 12 bits since 2^12 = 4096) that specify the exact byte within the page. Importantly, the Page Offset is never modified during address translation; it is copied directly to the physical address.

Demand Paging is a policy where pages are loaded into physical memory only when they are referenced during program execution, rather than loading the entire process image at startup. When a process references a page whose Valid-Invalid bit in the Page Table Entry (PTE) is set to 0 (invalid/not resident), the hardware triggers a Page Fault trap to the operating system kernel.`,
      },
      {
        title: "Lecture 2: Translation Lookaside Buffer (TLB) & Effective Access Time",
        body: `Because the Page Table itself is stored in main physical memory, every single memory reference by the CPU would normally require two physical memory accesses: one to read the Page Table Entry (PTE) and a second to access the actual requested data byte. This doubles memory access latency.

To solve this bottleneck, modern processors include a specialized, high-speed associative hardware cache called the Translation Lookaside Buffer (TLB). Each TLB entry stores a recently used (Virtual Page Number, Physical Frame Number) pair along with protection bits and an Address Space Identifier (ASID).

Effective Access Time (EAT) Formula:
Let alpha be the TLB Hit Ratio (for example, 0.98 or 98%), t_tlb be the TLB lookup time, and t_mem be the main memory access time.
When a TLB Hit occurs, total access time is (t_tlb + t_mem) in sequential lookup, or simply t_mem in parallel lookup.
When a TLB Miss occurs (with probability 1 - alpha), the MMU must access main memory to read the page table entry and then access main memory again for the target word, taking (t_tlb + 2 * t_mem).
Therefore, the Effective Access Time formula is:
EAT = alpha * (t_tlb + t_mem) + (1 - alpha) * (t_tlb + 2 * t_mem).

Common Student Mistake: Students frequently forget to multiply main memory access time by 2 on a TLB miss, or confuse a TLB Miss with a Page Fault. A TLB Miss only means the translation is not in the fast hardware cache; the page may still be resident in physical RAM. A Page Fault means the page is not in physical RAM at all and must be fetched from secondary disk/SSD storage.`,
      },
      {
        title: "Lecture 3: Page Replacement Algorithms & Thrashing",
        body: `When a Page Fault occurs and all physical frames in RAM are currently occupied, the operating system must select a victim frame to evict using a Page Replacement Algorithm. If the victim page has its Dirty Bit (Modify Bit) set to 1, it must be written back to swap space on disk before the new page overwrites the frame.

1. Optimal (OPT / Belady's Min) Algorithm:
Replaces the page that will not be used for the longest period of time in the future. It guarantees the lowest possible page fault rate for a fixed number of frames, but it is impossible to implement in practice because it requires future knowledge of reference strings. It serves as a theoretical benchmark.

2. First-In First-Out (FIFO) & Belady's Anomaly:
FIFO evicts the oldest page in memory. Counter-intuitively, FIFO suffers from Belady's Anomaly: for certain reference strings (such as 1, 2, 3, 4, 1, 2, 5, 1, 2, 3, 4, 5), increasing the number of allocated physical frames actually increases the total number of page faults.

3. Least Recently Used (LRU):
Evicts the page that has not been referenced for the longest time in the past, exploiting temporal locality. Because true LRU belongs to the class of stack algorithms, LRU never suffers from Belady's Anomaly. Since exact LRU hardware timestamps are expensive, operating systems use the Clock (Second-Chance) Algorithm with a single Reference Bit.

Thrashing & Working Set Model (Peter Denning):
Thrashing occurs when a process spends more time paging (swapping pages in and out of disk) than executing actual CPU instructions. This happens when the sum of the Working Sets of active processes exceeds total physical memoryframes. The Working Set W(t, delta) is the set of distinct pages referenced by a process during the most recent delta virtual time units. To prevent thrashing, the OS uses Working Set tracking or Page Fault Frequency (PFF) control to suspend processes when free frames drop below a critical threshold.`,
      },
    ],
  },
  {
    id: "ml_neural_nets",
    label: "CS 420: Machine Learning — Gradient Descent & Backpropagation.pdf",
    courseTag: "CS 420 Machine Learning",
    filename: "CS420_Gradient_Descent_Backprop_Regularization.pdf",
    pages: [
      {
        title: "Module 1: Empirical Risk Minimization & Gradient Descent Variants",
        body: `In supervised machine learning, given a training dataset of N input-output pairs (x_i, y_i), our objective is Empirical Risk Minimization: finding model parameters theta that minimize the average loss function J(theta) = (1/N) * sum L(f(x_i; theta), y_i).

Gradient Descent updates parameters iteratively in the opposite direction of the gradient of the objective function:
theta_{t+1} = theta_t - eta * grad J(theta_t), where eta > 0 is the learning rate (step size).

Comparison of Gradient Descent Variants:
1. Batch Gradient Descent: Computes the exact gradient using all N training examples in every single step. Guaranteed to converge to the global minimum for convex surfaces, but computationally prohibitive for large datasets.
2. Stochastic Gradient Descent (SGD): Approximates the gradient using a single randomly sampled training example per step. Updates have high variance, which causes the objective value to fluctuate, but this noise helps escape shallow local minima and saddle points.
3. Mini-Batch Gradient Descent: Computes the gradient on a small subset of B examples (typically B = 32, 64, or 128). Balances vectorization hardware efficiency on GPUs with rapid convergence.

Learning Rate Pitfalls: If eta is too small, convergence requires an excessive number of epochs. If eta is too large, the optimization overshoots the valley and diverges (loss explodes to infinity).`,
      },
      {
        title: "Module 2: Backpropagation, Vanishing Gradients & Regularization",
        body: `Backpropagation is an efficient application of the multivariable calculus Chain Rule paired with dynamic programming (caching intermediate forward-pass activations) to compute partial derivatives dL / dW_l for all weight matrices W_l in a deep neural network in a single backward pass.

During the forward pass, each layer computes pre-activation z_l = W_l * a_{l-1} + b_l and activation a_l = sigma(z_l). During the backward pass, the error signal delta_l = dL / dz_l is propagated backward from the output layer to the first hidden layer:
delta_l = (W_{l+1}^T * delta_{l+1}) hadamard_product sigma'(z_l).

The Vanishing Gradient Problem:
When traditional saturating activation functions like the logistic Sigmoid sigma(z) = 1 / (1 + e^{-z}) are used in deep networks, the maximum value of the derivative sigma'(z) is only 0.25 (at z = 0). Multiplying many terms <= 0.25 across L layers causes gradients in early layers to shrink exponentially toward zero, halting learning in early feature extractors.
Solution: Rectified Linear Unit (ReLU), defined as ReLU(z) = max(0, z), has a constant derivative of 1 for all z > 0, preventing gradient attenuation, though neurons with z < 0 can suffer from the Dying ReLU problem (solved by Leaky ReLU or GELU).

Bias-Variance Tradeoff & L1 vs L2 Regularization:
Overfitting occurs when a model has low training error but high generalization test error (high variance).
- L2 Regularization (Ridge / Weight Decay): Adds lambda * sum(w_j^2) to the loss. Penalizes large weights smoothly and shrinks weights proportionally toward zero without making them exactly zero.
- L1 Regularization (Lasso): Adds lambda * sum(|w_j|) to the loss. Because its subgradient is constant (+/- lambda), L1 induces sparsity by driving irrelevant feature weights to exactly zero, performing automatic feature selection.`,
      },
    ],
  },
];
